#!/bin/bash
testfile=(0_arr_defn2.out            41_index_arithmetic_expr.out
00_arr_defn2.sy             41_index_arithmetic_expr.sy
00_main.out                 42_index_func_ret.out
00_main.sy                  42_index_func_ret.sy
01_var_defn.out             43_time_prior_plus.out
01_var_defn.sy              43_time_prior_plus.sy
02_arr_defn4.out            44_add_prior_equal.out
02_arr_defn4.sy             44_add_prior_equal.sy
02_var_defn2.out            45_equal_prior_logic.out
02_var_defn2.sy             45_equal_prior_logic.sy
03_arr_defn.out             46_and_prior_or.out
03_arr_defn.sy              46_and_prior_or.sy
03_var_defn2.out            47_minus_with_sub.out
03_var_defn2.sy             47_minus_with_sub.sy
04_const_defn.out           49_decl_in_defn.out
04_const_defn.sy            49_decl_in_defn.sy
04_func_defn.out            50_recursion_test1.out
04_func_defn.sy             50_recursion_test1.sy
05_add.out                  51_recursion_test2.out
05_add.sy                   51_recursion_test2.sy
05_const_array_defn.out     52_recursion_test3.out
05_const_array_defn.sy      52_recursion_test3.sy
06_mod.out                  53_sort_test1.out
06_mod.sy                   53_sort_test1.sy
06_var_defn_func.out        54_sort_test2.out
06_var_defn_func.sy         54_sort_test2.sy
07_comment1.out             55_sort_test3.out
07_comment1.sy              55_sort_test3.sy
07_return_var.out           56_sort_test4.out
07_return_var.sy            56_sort_test4.sy
08_arr_assign.out           57_sort_test5.out
08_arr_assign.sy            57_sort_test5.sy
08_comment2.out             58_sort_test6.out
08_comment2.sy              58_sort_test6.sy
09_if.out                   59_sort_test7.out
09_if.sy                    59_sort_test7.sy
09_void_func.out            60_while_fibonacci.in
09_void_func.sy             60_while_fibonacci.out
10_break.out                60_while_fibonacci.sy
10_break.sy                 61_rec_fibonacci.in
10_if_else.out              61_rec_fibonacci.out
10_if_else.sy               61_rec_fibonacci.sy
11_continue.out             62_long_code.out
11_continue.sy              62_long_code.sy
11_while.out                63_simple_atoi.in
11_while.sy                 63_simple_atoi.out
12_array_traverse.out       63_simple_atoi.sy
12_array_traverse.sy        64_alpha_count.in
12_getint.in                64_alpha_count.out
12_getint.out               64_alpha_count.sy
12_getint.sy                65_word_count.in
13_and.in                   65_word_count.out
13_and.out                  65_word_count.sy
13_and.sy                   66_go_upstairs.out
13_array_traverse2.out      66_go_upstairs.sy
13_array_traverse2.sy       67_remove_duplicate_element.out
14_or.in                    67_remove_duplicate_element.sy
14_or.out                   68_accumulate.out
14_or.sy                    68_accumulate.sy
15_array_test3.out          69_last_word_length.out
15_array_test3.sy           69_last_word_length.sy
15_equal.in                 70_multi.out
15_equal.out                70_multi.sy
15_equal.sy                 71_max_subsequence_sum.out
16_greater_eq.out           71_max_subsequence_sum.sy
16_greater_eq.sy            72_enum.out
16_nequal.in                72_enum.sy
16_nequal.out               73_exchange_value.in
16_nequal.sy                73_exchange_value.out
17_less_eq.out              73_exchange_value.sy
17_less_eq.sy               74_itera_sqrt.out
17_less.in                  74_itera_sqrt.sy
17_less.out                 75_max_container.out
17_less.sy                  75_max_container.sy
18_cal_prio.in              76_int_factor_sum.out
18_cal_prio.out             76_int_factor_sum.sy
18_cal_prio.sy              77_unique_path.out
19_neg_expr.in              77_unique_path.sy
19_neg_expr.out             78_decbinoct.out
19_neg_expr.sy              78_decbinoct.sy
20_arr_sum.in               79_gcd.in
20_arr_sum.out              79_gcd.out
20_arr_sum.sy               79_gcd.sy
21_suminput.in              80_lcm.in
21_suminput.out             80_lcm.out
21_suminput.sy              80_lcm.sy
22_if_test1.out             81_jump_game.out
22_if_test1.sy              81_jump_game.sy
23_if_test2.out             82_int_split.out
23_if_test2.sy              82_int_split.sy
24_if_test3.out             83_enc_dec.out
24_if_test3.sy              83_enc_dec.sy
25_if_test4.out             84_palindrome_number.out
25_if_test4.sy              84_palindrome_number.sy
26_if_test5.out             86_bin_search.in
26_if_test5.sy              86_bin_search.out
27_while_test1.out          86_bin_search.sy
27_while_test1.sy           88_array_concat.out
28_while_test2.out          88_array_concat.sy
28_while_test2.sy           90_insert_order.in
29_while_test3.out          90_insert_order.out
29_while_test3.sy           90_insert_order.sy
30_while_if_test1.out       91_line_search.in
30_while_if_test1.sy        91_line_search.out
31_while_if_test2.out       91_line_search.sy
31_while_if_test2.sy        92_matrix_add.out
32_while_if_test3.out       92_matrix_add.sy
32_while_if_test3.sy        93_matrix_sub.out
33_func_test1.out           93_matrix_sub.sy
33_func_test1.sy            94_matrix_mul.out
34_func_test2.out           94_matrix_mul.sy
34_func_test2.sy            95_matrix_tran.out
35_array_test.out           95_matrix_tran.sy
35_array_test.sy            96_many_param_call.out
36_domain_test.out          96_many_param_call.sy
36_domain_test.sy           97_many_global_var.out
38_if_complex_expr.out      97_many_global_var.sy
38_if_complex_expr.sy       98_many_local_var.in
39_assign_complex_expr.out  98_many_local_var.out
39_assign_complex_expr.sy   98_many_local_var.sy
40_index_complex_expr.out   99_register_realloc.out
40_index_complex_expr.sy    99_register_realloc.sy)
str1=sy
for ((i=0;i<244;i++))
do
if [[ ${testfile[$i]} =~ $str1 ]] ; then
    	echo ${testfile[$i]}
	./parser ./functional_test/${testfile[$i]}
	echo -e "\n"
fi
done

